### ISSUE TITLE
Issue with the code

### ISSUE THREAD

**Issue by gameblabla** [JohnnyonFlame/sm64-od-port#1]
https://github.com/JohnnyonFlame/sm64-od-port/blob/od-port-beta/src/pc/fsutils.c#L16

it should be 
snprintf(fnamepath, sizeof(fnamepath), "%s/.sm64-port/", path);
instead of 
snprintf(fnamepath, sizeof(fnamepath), "%s/.sm64-port/", path, filename);

Because you are trying to create a folder, not a file.
Also the fact is missing #include <stdlib.h> so the compiler will miscompile it if its absent.

**Comment by JohnnyonFlame** [comment]
Good catch.

**Comment by JohnnyonFlame** [comment]
Fixed, thank you.
