### ISSUE TITLE
Puppycam joystick problem

### ISSUE THREAD

**Issue by Txori** [JohnnyonFlame/sm64-od-port#3]
Hi, first of all, great port.
I tried the fork of your project for RG351P (https://github.com/AdrienLombard/sm64-351elec-port) but there are some problems with the puppycam patch which makes the game barely playable:

Most of the time, I can't move the camera to the left and directly to the right. I need to move it up or down between left and right, otherwise it won't move. The same goes for up to down. I need to go either left or right between those.
There is no problem if I keep rotating the joystick. But if I release it to center position, I must do this weird manipulation to unlock the camera movement.

**Comment by JohnnyonFlame** [comment]
I haven't experienced this myself on the target platforms I maintain. Sorry.

**Comment by Txori** [comment]
Thanks for your response.
As there's no way to report an issue on the fork I mentioned, and since puppycam.diff is the exact same file apart from ```line 2212:  #ifndef TARGET_RG351```, I thought the problem might be coming from above.

I'll try to reach AdrienLombard differently to see if he has this problem :)

**Comment by JohnnyonFlame** [comment]
I'm closing this for now, if you do end up finding out that this somehow also affects this version I'll reopen and have a look. Thanks.
