### ISSUE TITLE
GameForce Chi?

### ISSUE THREAD

**Issue by gingerbeardman** [JohnnyonFlame/sm64-od-port#6]
Thanks for the SM64 port builder.

I ran it and got an opk

But I have no idea how to use it on my GameForce Chi. 

Can I just confirm that it should work on my device before I go deeper into this?

Also, I expected to find an sm64.sh but it's not in the current files output from the boiler?

**Comment by JohnnyonFlame** [comment]
You're looking for the RK3326 builder, this one is for OpenDingux devices. It's not going to work on your device.

**Comment by JohnnyonFlame** [comment]
Try this one: https://retrogamecorps.com/2020/12/28/guide-super-mario-64-port-on-rg351p/ It should be similar, biggest difference is that on EmuELEC you need to copy the sh file into `ports_scripts`.

**Comment by gingerbeardman** [comment]
Thanks so much! Success loading it.

I'll need to create a new button map.
